// Crop salt tolerance database
// ECe = EC of soil saturation extract at which 50% yield reduction occurs
// Sources: FAO guidelines for salt-tolerant crops

export const cropDatabase = [
  // Very tolerant (ECe threshold > 8 dS/m)
  {
    id: 'barley',
    name: 'Barley',
    scientificName: 'Hordeum vulgare',
    category: 'Cereal',
    toleranceLevel: 'very-high',
    ecThreshold50: 13.0, // dS/m — 50% yield loss
    ecMaxTolerable: 8.0, // dS/m — threshold above which stress begins
    yieldReduction: '10% per dS/m above 8',
    idealSoilTypes: ['sandy', 'sandy-loam', 'loamy'],
    waterRequirement: 'low',
    season: 'Rabi (winter)',
    notes: 'Excellent choice for saline soils. Best alternative when wheat fails.',
    icon: '🌾',
  },
  {
    id: 'cotton',
    name: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    category: 'Cash Crop',
    toleranceLevel: 'high',
    ecThreshold50: 9.6,
    ecMaxTolerable: 7.7,
    yieldReduction: '5.2% per dS/m above 7.7',
    idealSoilTypes: ['sandy-loam', 'loamy', 'clay'],
    waterRequirement: 'moderate',
    season: 'Kharif (monsoon)',
    notes: 'Reasonably tolerant. Drip irrigation dramatically reduces salinity stress.',
    icon: '🌿',
  },
  {
    id: 'sugar-beet',
    name: 'Sugar Beet',
    scientificName: 'Beta vulgaris',
    category: 'Cash Crop',
    toleranceLevel: 'very-high',
    ecThreshold50: 15.0,
    ecMaxTolerable: 7.0,
    yieldReduction: '5.9% per dS/m above 7',
    idealSoilTypes: ['loamy', 'clay-loam'],
    waterRequirement: 'moderate',
    season: 'Rabi (winter)',
    notes: 'One of the most salt-tolerant crops. Suitable for severely saline soils.',
    icon: '🌱',
  },
  {
    id: 'safflower',
    name: 'Safflower',
    scientificName: 'Carthamus tinctorius',
    category: 'Oilseed',
    toleranceLevel: 'high',
    ecThreshold50: 9.9,
    ecMaxTolerable: 5.3,
    yieldReduction: '6.2% per dS/m above 5.3',
    idealSoilTypes: ['sandy', 'sandy-loam', 'loamy'],
    waterRequirement: 'low',
    season: 'Rabi (winter)',
    notes: 'Drought and salt tolerant. Good oilseed alternative.',
    icon: '🌻',
  },
  // Moderately tolerant (ECe 4–8 dS/m)
  {
    id: 'wheat',
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    category: 'Cereal',
    toleranceLevel: 'moderate',
    ecThreshold50: 7.4,
    ecMaxTolerable: 6.0,
    yieldReduction: '7.1% per dS/m above 6',
    idealSoilTypes: ['loamy', 'clay-loam'],
    waterRequirement: 'moderate',
    season: 'Rabi (winter)',
    notes: 'Moderately tolerant. Yields significantly impacted above 6 dS/m.',
    icon: '🌾',
  },
  {
    id: 'sorghum',
    name: 'Sorghum (Jowar)',
    scientificName: 'Sorghum bicolor',
    category: 'Cereal',
    toleranceLevel: 'moderate',
    ecThreshold50: 7.2,
    ecMaxTolerable: 6.8,
    yieldReduction: '16% per dS/m above 6.8',
    idealSoilTypes: ['sandy-loam', 'loamy', 'clay'],
    waterRequirement: 'low',
    season: 'Kharif (monsoon)',
    notes: 'Drought tolerant. Acceptable in moderately saline conditions.',
    icon: '🌿',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    category: 'Oilseed',
    toleranceLevel: 'moderate',
    ecThreshold50: 6.7,
    ecMaxTolerable: 4.8,
    yieldReduction: '5% per dS/m above 4.8',
    idealSoilTypes: ['sandy-loam', 'loamy'],
    waterRequirement: 'moderate',
    season: 'Kharif / Rabi',
    notes: 'Moderately tolerant. Good alternative to mustard in saline regions.',
    icon: '🌻',
  },
  {
    id: 'mustard',
    name: 'Mustard (Rapeseed)',
    scientificName: 'Brassica juncea',
    category: 'Oilseed',
    toleranceLevel: 'moderate',
    ecThreshold50: 6.0,
    ecMaxTolerable: 3.0,
    yieldReduction: '9.0% per dS/m above 3',
    idealSoilTypes: ['sandy', 'sandy-loam'],
    waterRequirement: 'low',
    season: 'Rabi (winter)',
    notes: 'Sensitive in early stages. Moderate tolerance at maturity.',
    icon: '🟡',
  },
  // Sensitive (ECe < 4 dS/m)
  {
    id: 'rice',
    name: 'Rice (Paddy)',
    scientificName: 'Oryza sativa',
    category: 'Cereal',
    toleranceLevel: 'low',
    ecThreshold50: 4.0,
    ecMaxTolerable: 3.0,
    yieldReduction: '12% per dS/m above 3',
    idealSoilTypes: ['clay', 'clay-loam'],
    waterRequirement: 'high',
    season: 'Kharif (monsoon)',
    notes: 'Very sensitive to salinity. Avoid in EC > 3 dS/m conditions.',
    icon: '🍚',
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    category: 'Cash Crop',
    toleranceLevel: 'low',
    ecThreshold50: 4.0,
    ecMaxTolerable: 1.7,
    yieldReduction: '5.9% per dS/m above 1.7',
    idealSoilTypes: ['loamy', 'clay-loam'],
    waterRequirement: 'high',
    season: 'Annual',
    notes: 'Sensitive to salinity. Not recommended in saline soils.',
    icon: '🎋',
  },
  {
    id: 'chickpea',
    name: 'Chickpea (Gram)',
    scientificName: 'Cicer arietinum',
    category: 'Legume',
    toleranceLevel: 'low',
    ecThreshold50: 3.0,
    ecMaxTolerable: 1.2,
    yieldReduction: '11.1% per dS/m above 1.2',
    idealSoilTypes: ['sandy-loam', 'loamy'],
    waterRequirement: 'low',
    season: 'Rabi (winter)',
    notes: 'Highly sensitive. Only suitable for low salinity soils.',
    icon: '🫘',
  },
  {
    id: 'lentil',
    name: 'Lentil (Masoor)',
    scientificName: 'Lens culinaris',
    category: 'Legume',
    toleranceLevel: 'low',
    ecThreshold50: 3.0,
    ecMaxTolerable: 1.5,
    yieldReduction: '9% per dS/m above 1.5',
    idealSoilTypes: ['loamy', 'sandy-loam'],
    waterRequirement: 'low',
    season: 'Rabi (winter)',
    notes: 'Sensitive to salinity. Not recommended above EC 2 dS/m.',
    icon: '🫘',
  },
];

export const getCropById = (id) => cropDatabase.find(c => c.id === id);

export const getCropsByTolerance = (level) => cropDatabase.filter(c => c.toleranceLevel === level);

export const getRecommendedCrops = (ec) => {
  return cropDatabase
    .filter(c => c.ecMaxTolerable >= ec)
    .sort((a, b) => b.ecMaxTolerable - a.ecMaxTolerable);
};
